# Generated by Django 5.2.8 on 2025-11-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['destination', 'name'], 'verbose_name': 'Alojamiento', 'verbose_name_plural': 'Alojamientos'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['country', 'city'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['destination', 'type'], 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
