# Generated by Django 5.2.8 on 2025-11-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_accommodation_options_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['itinerary', 'name'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['name'], 'verbose_name': 'Guía', 'verbose_name_plural': 'Guías'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['plan', 'day'], 'verbose_name': 'Itinerario', 'verbose_name_plural': 'Itinerarios'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo extra'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.itinerary', verbose_name='Itinerario'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.IntegerField(verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
